// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'modules/search/data/repositories/search_repository_impl_test.dart' as modules_search_data_repositories_search_repository_impl_test;
import 'modules/search/domain/usescases/search_by_text_test.dart' as modules_search_domain_usescases_search_by_text_test;

void main() {
  modules_search_data_repositories_search_repository_impl_test.main();
  modules_search_domain_usescases_search_by_text_test.main();
}
